locator:
  image: apachegeode/geode:1.0.0-incubating.M1
  hostname: locator
  mem_limit: 512m
  expose:
   - "10334"
   - "1099"
   - "7575"
  #  - "1024"
  ports:
   - "1099:1099"
   - "10334:10334"
   - "7575:7575"
   - "7070:7070"
  volumes:
   - ./scripts/:/scripts/
  command: /scripts/gfshWrapper.sh gfsh start locator --J="-Dgemfire.jmx-manager-hostname-for-clients=192.168.99.100" --hostname-for-clients=192.168.99.100 --name=locator --mcast-port=0

server:
  image: apachegeode/geode:1.0.0-incubating.M1
  mem_limit: 2g
  links:
   - locator:locator
  expose:
   - "8080"
   - "40404"
   - "1099"
  ports:
   - "40404:40404"
  volumes:
   - ./scripts/:/scripts/
  command: /scripts/startServer.sh --server-port=40404 --hostname-for-clients=192.168.99.100 --max-heap=1G
